# Generated by Django 5.2 on 2025-04-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_text', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'Logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_text', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('entered_at', models.DateTimeField()),
                ('exit_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'PlayerLogs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('hash_password', models.CharField(max_length=100)),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Players',
                'managed': False,
            },
        ),
    ]
